version: '2'

services:

  mongo:
    image: mongo
    container_name: mongo
    ports:
     - '27017:27017'
    command: "--smallfiles --logpath=/dev/null"

networks:
  default:
    external:
      name: local

